=== pypi-data/pypi-mirror-366/packages/hyrrokkin/hyrrokkin-0.1.2.tar.gz/hyrrokkin-0.1.2/src/hyrrokkin/tools/package_validation/package_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "package_schema.json",
  "title": "JSONSchema description of Packages",
  "description": "Specify how Packages are defined in JSON",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "metadata",
    "node_types"
  ],
  "$defs": {
    "link_type": {
      "description": "Specify how Link Types are defined in JSON",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "metadata"
      ],
      "properties": {
        "metadata": {
          "type": "object",
          "description": "Attach metadata to this link type",
          "required": [
            "name"
          ],
          "additionalProperties": true,
          "properties": {
            "name": {
              "type": "string",
              "description": "Provide a short descriptive name for this link type"
            },
            "description": {
              "type": "string",
              "description": "Provide a short description (~1 paragraph) of the purpose of this link type"
            }
          }
        },
        "display": {
          "type": "object",
          "properties": {
            "colour": {
              "type": "string",
              "description": "Specify a colour for this link type, used when drawing networks as a diagram"
            }
          }
        },
        "transport": {
          "enum": ["stream", "iterator" ],
          "description": "optional, specify if this link type carries a stream or iterator of values"
        }
      }
    },
    "node_type": {
      "description": "Specify how Node Types are defined in JSON",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "metadata": {
          "type": "object",
          "description": "Attach metadata to this node type",
          "required": [
            "name"
          ],
          "additionalProperties": true,
          "properties": {
            "name": {
              "type": "string",
              "description": "Provide a short descriptive name for this node type"
            },
            "description": {
              "type": "string",
              "description": "Provide a short description (~1 paragraph) of the purpose of this node type"
            }
          }
        },
        "clients": {
          "type": "object",
          "description": "Define clients of this node - specify a mapping from client name to its definition",
          "patternProperties": {
            ".*": {
              "type": "object"
            }
          }
        },
        "input_ports": {
          "type": "object",
          "description": "Specify a mapping from an input port name to its definition",
          "patternProperties": {
            ".*": {
              "type": "object",
              "properties": {
                "link_type": {
                  "type": "string",
                  "description": "the link type of the port, qualified with the package name"
                },
                "allow_multiple_connections": {
                  "type": "boolean",
                  "description": "whether this port allows more than one connection to other ports, defaults to false"
                }
              }
            }
          }
        },
        "output_ports": {
          "type": "object",
          "description": "Specify a mapping from an output port name to its definition",
          "patternProperties": {
            ".*": {
              "type": "object",
              "properties": {
                "link_type": {
                  "type": "string",
                  "description": "the link type of the port, qualified with the package name"
                },
                "allow_multiple_connections": {
                  "type": "boolean",
                  "description": "whether this port allows more than one connection to other ports, defaults to false"
                }
              }
            }
          }
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string",
      "description": "Provide a unique id for this package"
    },
    "configuration": {
      "type": "object",
      "description": "Specify code that handles the package configuration",
      "properties": {
        "clients": {
          "type": "object",
          "description": "Define clients of this package's configuration - specify a mapping from client name to its definition",
          "patternProperties": {
            ".*": {
              "type": "object"
            }
          }
        }
      }
    },
    "metadata": {
      "type": "object",
      "description": "Attach metadata to this package",
      "required": [
        "name"
      ],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "description": "Provide a short descriptive name of this package"
        },
        "description": {
          "type": "string",
          "description": "Provide a short description (~1 paragraph) of the purpose of this package"
        },
        "version": {
          "type": "string",
          "description": "Specify the version of the package"
        }
      }
    },
    "display": {
      "type": "object",
      "description": "Specify how nodes in this package are displayed in a network diagram",
      "properties": {
        "icon": {
          "description": "Provide the URL of a SVG icon, relative to the package",
          "type": "string"
        },
        "corners": {
          "description": "Define the shape of the node, in terms of the number of corners",
          "type": "integer"
        },
        "style": {
          "description": "Specify CSS styles to apply to this node's icon",
          "type": "string"
        }
      }
    },
    "node_types": {
      "type": "object",
      "description": "mapping from a node type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "#/$defs/node_type"
        }
      }
    },
    "link_types": {
      "type": "object",
      "description": "mapping from a link type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "#/$defs/link_type"
        }
      }
    }
  }
}

=== pypi-data/pypi-mirror-366/packages/telesto/telesto-0.0.6-py3-none-any.whl/telesto/example_packages/textgraph/schema.json
{
    "id": "textgraph",
    "metadata": {
        "name": "Text Graph",
        "version": "0.0.1",
        "description": "a toy example package for analysing text"
    },
    "node_types": {
        "text_input_node": {
            "metadata": {
                "name": "Text Input",
                "description": "Input a text document to be analysed"
            },
            "output_ports": {
                "data_out": {
                    "link_type": "textgraph:text",
                    "allow_multiple_connections": true
                }
            },
            "display": {
                "corners": 8,
                "icon": "icons/text_input_node.svg"
            },
            "clients": {
                "default": {
                    "menu_label":"Open...",
                    "title": "Input Text",
                    "url": "html/text_input_node.html",
                    "window_width": 500,
                    "window_height": 300
                }
            }
        },
        "word_frequency_node": {
            "metadata": {
                "name": "Word Frequency",
                "description": "Calculate the frequencies of words in the input text"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "textgraph:text",
                    "allow_multiple_connections": false
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "textgraph:table",
                    "allow_multiple_connections": true
                }
            },
            "display": {
                "corners": 8,
                "icon": "icons/word_frequency_node.svg"
            },
            "clients": {
                "default": {
                    "menu_label":"Open...",
                    "title": "Word Frequency Node",
                    "url": "html/word_frequency_node.html",
                    "window_width": 500,
                    "window_height": 300
                }
            }
        },
        "table_display_node": {
            "metadata": {
                "name": "Table Display",
                "description": "Display tabular data containing the results of analysing text"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "textgraph:table",
                    "allow_multiple_connections": false
                }
            },
            "display": {
                "corners": 8,
                "icon": "icons/table_display_node.svg"
            },
            "clients": {
                "default": {
                    "menu_label":"Open...",
                    "title": "Table Display",
                    "url": "html/table_display_node.html",
                    "window_width": 500,
                    "window_height": 300
                }
            }
        }
    },
    "link_types": {
        "text": {
            "metadata": {
                "name": "Text",
                "description": "This type of link carries text values"
            }
        },
        "table": {
            "metadata": {
                "name": "Table",
                "description": "This type of link carries values that are tables (lists of lists)"
            }
        }
    }
}
